import Head from "next/head";
import Link from "next/link";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Page Not Found</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen py-28 text-dark gap-4 text-center">
        <h1 className="text-6xl md:text-[7vw] font-morionBold font-bold  tracking-widest py-10">
          404
        </h1>
        <h2 className=" text-3xl md:text-5xl font-questa font-bold capitalize ">
          Page You Are Looking For does not exist.
        </h2>
        <div className=" d pt-16 pb-10  ">
          <Link passHref href="/">
            <a className="bg-black text-white font-morion  text-2xl md:text-3xl ml-auto py-4 border  hover:border-dark hover:bg-white hover:text-black transition-colors duration-200 ">
              Return To Home
            </a>
          </Link>
        </div>
      </div>
    </div>
  );
}
