import Head from "next/head";
import { BannerAbout } from "../blades/about";
export default function About() {
  return (
    <div>
      <Head>
        <title>about page </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BannerAbout />
    </div>
  );
}
