import Head from "next/head";
import { BannerProjects } from "../blades/projects";
export default function Home() {
  return (
    <div>
      <Head>
        <title>projects Page </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-20">
        <BannerProjects />
      </div>
    </div>
  );
}
