import Head from "next/head";

import {
  BannerThoughts,
  MasterBlog,
  BlogCard,
  BlogTile,
} from "../blades/thoughts";

const tags = ["React", "JavaScript", "Next.js", "CSS", "Animation", "Node"];
export default function About() {
  const Tag = ({ data }) => {
    return (
      <div className="border border-gray-300 bg-gray-50 font-averta  px-6 py-[6px] rounded-full hover:bg-gray-200 cursor-pointer text-sm md:text-base">
        {data}
      </div>
    );
  };

  return (
    <div className="max-w-[120rem] md:w-11/12 mx-auto px-1">
      <Head>
        <title>thoughts page </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-20">
        <BannerThoughts bannerText={["t", "h", "o", "u", "g", "h", "t", "s"]} />
        <div className=" max-w-7xl mx-auto">
          <MasterBlog />
          <section className="flex flex-wrap gap-x-10 gap-y-12 pt-4 md:pt-10 lg:pt-16 px-1">
            <BlogCard />
            <BlogCard />
          </section>
          <section className="flex flex-wrap gap-x-16 border-t border-gray-300 mt-16  px-1 ">
            <div className="basis-[30rem] grow shrink divide-y divide-gray-300 py-2 md:py-3 lg:py-6">
              <BlogTile />
              <BlogTile />
              <BlogTile />
              <BlogTile />
              <BlogTile />
            </div>
            <aside className="basis-96 max-w-lg grow shrink my-3 py-4  px-1 md:py-10">
              <div className="flex flex-nowrap gap-2 stroke-gray-600 border border-gray-300 rounded-full pl-4 overflow-hidden ">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-6 w-6 my-3"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="inherit"
                  strokeWidth="2"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
                  />
                </svg>
                <input
                  type="text"
                  placeholder="Search"
                  className="bg-white text-black font-averta text-lg  placeholder:text-gray-700 font-light px-1  outline-none focus:text-blue flex-1"
                  size="2"
                />
              </div>
              <div className="flex flex-wrap gap-2 md:gap-3 md:py-4 lg:py-8 items-start justify-start">
                <h3 className="min-w-full text-2xl font-bold font-averta pb-2 pt-4  md:pb-4 md:pt-6 px-1 ">
                  Recommended Topics
                </h3>
                {tags.map((i, index) => {
                  return <Tag data={i} key={index} />;
                })}
              </div>
            </aside>
          </section>
        </div>
      </div>
    </div>
  );
}
